### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by lyvvq9296** [SKHon/koa-book-code#1]
router.post('/upload', async (ctx) => {
	// 获取文件对象
	const file = ctx.request.files.file
	// 读取文件内容
	const data = fs.readFileSync(file.path);
	// 保存到服务端
	fs.writeFileSync(path.join(__dirname, file.name), data);
	ctx.body = { message: '上传成功！' };
})

const file = ctx.request.files.file 中 file 对象没有 path 属性,导致读取文件报错

**Comment by lyvvq9296** [comment]
2-2上传和下载章节, 上传接口该改成这样
```
router.post('/upload', async (ctx) => {
	// 获取文件对象
	const file = ctx.request.files.file

	const data = fs.readFileSync(`${file.filepath}`);
	// 保存到服务端
	fs.writeFileSync(path.join(__dirname, file.originalFilename), data);
	ctx.body = { message: '上传成功！'};
})
```

**Comment by SKHon** [comment]
@ziyi-joiede 同学你好，我又看了一下源码，验证了一下。我这里拿到的file对象是这样的：
File {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  size: 267147,
  path:
   '/var/folders/vz/mzl4dwvx56d7crn100cf24840000gn/T/upload_fb4a40ad9ab306209e7d349721cc58ca',
  name: 'koa.png',
  type: 'image/png',
  hash: null,
  lastModifiedDate: 2022-06-29T00:41:13.986Z,
  _writeStream:
   WriteStream {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        emitClose: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     path:
      '/var/folders/vz/mzl4dwvx56d7crn100cf24840000gn/T/upload_fb4a40ad9ab306209e7d349721cc58ca',
     fd: null,
     flags: 'w',
     mode: 438,
     start: undefined,
     autoClose: true,
     pos: undefined,
     bytesWritten: 267147,
     closed: false } }
所以file.path是ok的，反而file.filepath是undefined。同学你再看一下

**Comment by lyvvq9296** [comment]
刚刚看了下，和koa-body的版本有关，我的是5.0.0版
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 6月29日 08:43，SKHon ***@***.***> 写道： 
   
  @ziyi-joiede 同学你好，我又看了一下源码，验证了一下。我这里拿到的file对象是这样的：
 File {
 _events: {},
 _eventsCount: 0,
 _maxListeners: undefined,
 size: 267147,
 path:
 '/var/folders/vz/mzl4dwvx56d7crn100cf24840000gn/T/upload_fb4a40ad9ab306209e7d349721cc58ca',
 name: 'koa.png',
 type: 'image/png',
 hash: null,
 lastModifiedDate: 2022-06-29T00:41:13.986Z,
 _writeStream:
 WriteStream {
 _writableState:
 WritableState {
 objectMode: false,
 highWaterMark: 16384,
 finalCalled: true,
 needDrain: false,
 ending: true,
 ended: true,
 finished: true,
 destroyed: true,
 decodeStrings: true,
 defaultEncoding: 'utf8',
 length: 0,
 writing: false,
 corked: 0,
 sync: false,
 bufferProcessing: false,
 onwrite: [Function: bound onwrite],
 writecb: null,
 writelen: 0,
 bufferedRequest: null,
 lastBufferedRequest: null,
 pendingcb: 0,
 prefinished: true,
 errorEmitted: false,
 emitClose: false,
 bufferedRequestCount: 0,
 corkedRequestsFree: [Object] },
 writable: false,
 _events: {},
 _eventsCount: 0,
 _maxListeners: undefined,
 path:
 '/var/folders/vz/mzl4dwvx56d7crn100cf24840000gn/T/upload_fb4a40ad9ab306209e7d349721cc58ca',
 fd: null,
 flags: 'w',
 mode: 438,
 start: undefined,
 autoClose: true,
 pos: undefined,
 bytesWritten: 267147,
 closed: false } }
 所以file.path是ok的，反而file.filepath是undefined。同学你再看一下
